# Generated by Django 5.0.3 on 2024-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_publish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Книжный номер'),
        ),
    ]
