# Generated by Django 5.0.3 on 2024-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=255, null=True, verbose_name='Книжный номер'),
        ),
    ]
