# Generated by Django 5.0.3 on 2024-04-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_publish_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
