# Generated by Django 5.0.3 on 2024-04-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_publish_date_in_publish_date_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
    ]
