# Generated by Django 5.0.3 on 2024-04-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_returnedbook_city_returnedbook_date_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedbook',
            name='additional_info',
        ),
    ]
