# Generated by Django 5.0.3 on 2024-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_returnedbook_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
