# Generated by Django 5.0.3 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_book_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(null=True, verbose_name='Год издания'),
        ),
    ]
