# Generated by Django 5.0.6 on 2024-10-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_book_year_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='news_photos/', verbose_name='Фото')),
            ],
        ),
    ]
