# Generated by Django 5.0.6 on 2024-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_returnedbook_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bbk',
            field=models.CharField(max_length=255, verbose_name='BBK'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Название книги'),
        ),
    ]
